POST http://localhost:5000/register
Content-Type: application/json

{
    "username":"Bax",
    "email":"ibax8@ycombinator.com",
    "password":"mkDq1CeIBx4C"
}




###
POST http://localhost:5000/login
Content-Type: application/json

{
      "email":"ibax8@ycombinator.com",
    "password":"mkDq1CeIBx4C"

}

###
POST http://localhost:5000/updateProfile
Content-Type: application/json

{
    "username":"mary",
    "email":"mary@mail.com",
    "password":"mary0"
}
