//Products
//Adding a product to database
POST http://localhost:8000/createProduct
Content-Type: application/json

{
    "productName":,
    "description",
    "price",
    "category",
    "productImage"
}
//Updating a product
###
PUT http://localhost:8000/updateProduct
Content-Type: application/json

{
    "productName":,
    "description":,
    "price":,
    "category":,
    "productImage":
}
//Getting all products from the database
###
GET http://localhost:8000/viewProducts
//Getting product by name
###
GET http://localhost:8000/Product/
//Orders
//Making an order
POST http://localhost:8000/createOrder
Content-Type: application/json

{
    "userId":,
    "productId":
    
}
