POST http://localhost:8000/product/createProduct
Content-Type: application/json

{
    "productName":"Generic Geneva Stylish Casual Watch",
    "description":"Generic Geneva Stylish Casual Watch",
    "price":"Ksh.9000.00",
    "category":"Watches",
    "productImage":"https://ke.jumia.is/unsafe/fit-in/300x300/filters:fill(white)/product/01/221883/1.jpg?0474"
}
//Updating a product
###
PUT http://localhost:8000/product/updateProduct
Content-Type: application/json

{
    "productId":1,
    "productName":"Modern bamboo wrist watch",
    "description":"Wooden watch with leather wrist band and black hands",
    "price":"Ksh.5600.00",
    "category":"Watches",
    "productImage":"https://image.kilimall.com/kenya/shop/store/goods/6188/2020/11/6188_06600882317941505_720.jpg.webp"
}
//Getting all products from the database
###
GET http://localhost:8000/product/viewProducts
//Getting product by name
###
GET http://localhost:8000/product/product/Modern bamboo wrist watch
//Orders 
//Making an order
###
POST http://localhost:8000/createOrder
Content-Type: application/json

{
    "userId":,
    "productId":
    
}
