POST http://localhost:5002/product/createProduct
Content-Type: application/json

{
    "productName":"car",
    "description":"Wooden watch with leather wrist band and black hands",
    "price":"Ksh.1000.00",
    "category":"Vehicles",
    "productImage":"https://burst.shopifycdn.com/photos/wrist-watches.jpg?width=746&format=pjpg&exif=1&iptc=1"
}
//Updating a product
###
PUT http://localhost:5002/product/updateProduct
Content-Type: application/json

{
    "productId":2,
    "productName":"Modern bamboo wrist watch",
    "description":"Wooden watch with leather wrist band and black hands",
    "price":"Ksh.1800.00",
    "category":"Wrist watches",
    "productImage":"https://burst.shopifycdn.com/photos/wrist-watches.jpg?width=746&format=pjpg&exif=1&iptc=1"
}
//Getting all products from the database
###
GET http://localhost:5002/product/pageProduct?row_count=2&page_number=2
//Getting product by name

###
GET http://localhost:5002/product/viewProducts
###
GET http://localhost:5002/product/product/car
//Orders 
//Making an order
###
POST http://localhost:8000/createOrder
Content-Type: application/json

{
    "userId":,
    "productId":
    
}
